NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
FEDERATION_SERVER="https://api.domain.com/federation"
AUTH_SERVER="https://api.domain.com/auth"
TRANSFER_SERVER="https://api.domain.com"
SIGNING_KEY="GBBHQ7H4V6RRORKYLHTCAWP6MOHNORRFJSDPXDFYDGJB2LPZUFPXUEW3"
HORIZON_URL="https://horizon.domain.com"
ACCOUNTS=[
"GD5DJQDDBKGAYNEAXU562HYGOOSYAEOO6AS53PZXBOZGCP5M2OPGMZV3",
"GAENZLGHJGJRCMX5VCHOLHQXU3EMCU5XWDNU4BGGJFNLI2EL354IVBK7",
"GAOO3LWBC4XF6VWRP5ESJ6IBHAISVJMSBTALHOQM2EZG7Q477UWA6L7U"
]
VERSION="2.0.0"

[DOCUMENTATION]
ORG_NAME="Sloth Coin"
ORG_DBA="Sloth Coin"
ORG_URL="https://slothcoin.github.io/"
ORG_LOGO="https://slothcoin.github.io/assets/slothcoin.png"
ORG_DESCRIPTION="Sloth Coinz"
ORG_PHYSICAL_ADDRESS="-"
ORG_KEYBASE="slothcoin"
ORG_TWITTER="slothcoin"
ORG_GITHUB="slothcoin"
ORG_OFFICIAL_EMAIL="sloth@mm.st"

[[CURRENCIES]]
code = "SLTH"
name = "Sloth Coin"
issuer = "GAVJZ63FH3ZOIMYPKI7R4DVWPTEALI6ATA5AJPOEUKQQNMLQVUDO6NLT"
is_asset_anchored = false
display_decimals = 7
desc="UDIN Token - Just For Fun"
image="https://slothcoin.github.io/assets/slothcoin.png"
conditions="There will only ever be 1 billion UDIN tokens in existence."
